[package]
name = "collabobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
eyre = "0.6.9"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "chrono", "migrate", "json"] }
surrealdb = "1.0.0"
surrealdb-migrations = { path = "../vendor/surrealdb-migrations" }
tokio = { version = "1.31.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
